export const cardStyles: Record<string, React.CSSProperties> = {
  card: {
    background: '#1e1e2e',
    border: '1px solid #313244',
    borderRadius: 8,
    padding: 24,
    width: 360,
  },
  heading: {
    fontSize: 15,
    fontWeight: 600,
    color: '#cba6f7',
    marginBottom: 20,
  },
  field: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    marginBottom: 12,
  },
  label: {
    fontSize: 11,
    color: '#a6adc8',
  },
  input: {
    background: '#181825',
    border: '1px solid #313244',
    borderRadius: 5,
    color: '#cdd6f4',
    fontFamily: 'inherit',
    fontSize: 13,
    padding: '7px 10px',
    outline: 'none',
  },
  button: {
    width: '100%',
    marginTop: 8,
    padding: '9px 12px',
    background: '#cba6f7',
    border: 'none',
    borderRadius: 5,
    color: '#1e1e2e',
    fontFamily: 'inherit',
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
  },
  buttonDisabled: {
    opacity: 0.4,
    cursor: 'not-allowed',
  },
  result: {
    marginTop: 16,
    padding: 12,
    borderRadius: 5,
    fontSize: 12,
  },
  resultSuccess: {
    background: '#1e3a2e',
    color: '#a6e3a1',
  },
  resultError: {
    background: '#3b1e1e',
    color: '#f38ba8',
  },
}
